### ISSUE TITLE
Hello, there are several questions I would like to ask, I have been making the following error

### ISSUE THREAD

**Issue by shuimoshusheng** [laurensarah2022/SCTP_Win32#1]
NMAKE : fatal error U1077: “"D:\Program Files\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files\Microsoft Visual Studio 14.0\VC\BIN\nmake.EXE"”: 返回代码“0x2”
Stop.

I have tried configuring environment variables but it doesn't work！
can you help me？

**Comment by SixthTitan** [comment]
From what I've gathered, that error may be due to installing a different arch processor type of Visual Studio. Try uninstalling Visual Studio and then installing Visual Studio x64 bit, both make and visual studio have to be installed with the same bit arch processor type. 

Note: I used this on Debian Linux (Ubuntu specifically), so am not sure how well this library works well with on windows.

Helpful Resource: https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/nmake-fatal-error-u1077?view=vs-2019
